fix: Workflow, appspec

diff --git a/.github/workflows/deployBE.yml b/.github/workflows/deployBE.yml
--- a/.github/workflows/deployBE.yml
+++ b/.github/workflows/deployBE.yml
@@ -26,6 +26,20 @@ jobs:
       - name: Build Gradle
         run: ./gradlew build
 
+      - name: Zip build file and deploy sh
+        run: |
+          mv ./build/libs/*.jar ./
+          zip monitor-assistant.zip ./deploy.sh ./appspec.yml ./*.jar
+
+      - name: Upload To S3
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOYMENT }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOYMENT }}
+        run: |
+          aws s3 cp \
+            --region us-east-1 \
+            monitor-assistant.zip s3://cscapstone-21-1-5-s3
+          
       - name: aws Configuration
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -33,8 +47,26 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOYMENT }}
           aws-region: us-east-1
 
-      - name: Upload To S3
-        run: aws deploy push --application-name BEDeployment --s3-location s3://cscapstone-21-1-5-s3/monitor-assistant.zip --source .
+      - name: Deploy ec2
+        run: |
+          aws deploy create-deployment \
+            --application-name BEDeployment \
+            --deployment-group-name BEDeployment \
+            --s3-location bucket=cscapstone-21-1-5-s3,key=monitor-assistant.zip,bundleType=zip > deploymentId.txt
 
-      - name: code deploy
-        run: aws deploy create-deployment --application-name BEDeployment --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name BEDeployment --s3-location bucket=cscapstone-21-1-5-s3,bundleType=zip,key=monitor-assistant.zip
+          DEPLOYMENT_ID=$(cat deploymentId.txt | jq -r '.deploymentId')
+
+          echo "Wait 60 seconds for deployment and test"
+          sleep 60
+
+          IS_SUCCESS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID | jq -r '.deploymentInfo.status')
+
+          echo $IS_SUCCESS;
+
+          if [ "$IS_SUCCESS" = "Succeeded" ];
+          then
+            echo "SUCCESS DEPLOY!"
+          else
+            echo "FAIL DEPLOY!"
+            exit 1
+          fi
